### ISSUE TITLE
Option action must be equal to one of: nothing, install, delete!  You passed :create

### ISSUE THREAD

**Issue by luis-alen** [sinfomicien/mysql2_chef_gem#14]
Hello,

Today I was changing a few things on my devbox cookbook when the following error suddenly started to happen with the mysql2_chef_gem cookbook.

`Option action must be equal to one of: nothing, install, delete!  You passed :create`

I've always used it as described in the docs and have never changed it:

```
mysql2_chef_gem 'default' do
  client_version '5.6'
  action :install
end
```

Then I decided to create a completely fresh cookbok depending only on mysql2_chef_gem, nothing else. Same error happened when I executed the code above on the default recipe.

I believe it has something to do with dependency compatibility. This cookbook requires mysql >=6.0 and a new version of the mysql cookbook has just been released. Coincidently the error started to happen approximately at the same time berkshelf downloaded the new version of the mysql cookbook, 8.0.0.

Removing my Berksfile.lock and adding `depends 'mysql' '~> 7.2'` to my metadata.rb fixed the issue, but this is probably something you might wanna check...

**Comment by marcomancuso** [comment]
Hello, I still have this exception and I have 

```
depends "mysql", ">= 6.0.21"
depends 'mysql2_chef_gem', ">= 1.0.1"
```

Has it been fixed?

**Comment by marcomancuso** [comment]
Hello, I still have this exception and I have 

```
depends "mysql", ">= 6.0.21"
depends 'mysql2_chef_gem', ">= 1.0.1"
```

Has it been fixed?

**Comment by marcomancuso** [comment]
Hello, I still have this exception and I have 

```
depends "mysql", ">= 6.0.21"
depends 'mysql2_chef_gem', ">= 1.0.1"
```

Has it been fixed?

**Comment by japitts0889** [comment]
@marcomancuso The correct syntax for that to work is below

`depends 'mysql', '~> 7.2'
`
You'll need to add that to your metadata until they can get the pull request merged.

**Comment by gsaslis** [comment]
same issue here - upvoting 👍

**Comment by pelletiermaxime** [comment]
Could you do a new release with the fix ? Thanks.

**Comment by nepomucen** [comment]
The same issue here

**Comment by tas50** [comment]
This has been fixed on master
