### ISSUE TITLE
Implicit mysql cookbook version dependency

### ISSUE THREAD

**Issue by frightenedmonkey** [sinfomicien/mysql2_chef_gem#2]
In my org, for reasons that would take too long to explain (if you're desperately curious, I can explain), we're stuck on an older version of the mysql community cookbook (3.0.x). The `mysql_client` LWRP was added in the mysql 5.0 cookbook. I am, however, upgrading our dependencies to use the newest database cookbook, which now uses this cookbook as a dep. 

The first time I converged a node during testing, I got a NoMethodError as the old mysql we're stuck with has no `mysql_client` resource. Here's the block in your provider:
https://github.com/sinfomicien/mysql2_chef_gem/blob/1a5d354074496b5e30e116dfc7df341518fb3e86/libraries/provider_mysql2_chef_gem_mysql.rb#L15-L19

I can work around this by declaring an empty `mysql_client` LWRP in my internal mysql cookbook to satisfy the requirement, and that's what I've done so far.

I see three possible solutions:
1. Just declare an explicit version dependency in your metadata
2. Remove the `mysql_client` resource in your provider
3. Some sort of begin/rescue or mysql cookbook version check to determine whether to apply the resource or the mysql::client recipe.

I'm more than happy to help with an initial implementation and to work with you to make it acceptable if you go for solution 3, but I don't know if you consider the issue that big of a deal. FWIW, I'm not entirely sure that you *need* the mysql dependency — this cookbook seems like more of a dependency on mysql rather than the other way around, although I may certainly be missing some context here. Beyond that, I'd really appreciate if you don't explicitly declare a version dependency in your metadata, too. Regardless, let me know if I can help!

**Comment by acm1** [comment]
+1

**Comment by aiman-alsari** [comment]
+1

**Comment by someara** [comment]
The dependency on the mysql cookbook here is to get access to the mysql_client resources here:

https://github.com/sinfomicien/mysql2_chef_gem/blob/master/libraries/provider_mysql2_chef_gem_mysql.rb#L16-L19

This creates a "tightly coupled" situation that can be resolved by Berkshelf and enforced by the chef-client.

The only way to remove the dependency would be to re-implement all the logic that selects the mysql_client package/version information for all the supported platforms, which supply the libraries needed to compile the mysql2 gem.

Removing the dependency without re-implementing all the logic from the mysql cookbook would create a "loosely coupled" situation, where things explode by default, then force users have to manually install the appropriate libraries needed to compile the gem.
I think

**Comment by someara** [comment]
A constraint tying this down to the 6.x version of mysql should be made.

I'm currently removing the tight coupling between the database cookbook and this one. (wip)

**Comment by xbeta** [comment]
+1 @someara

**Comment by eric-tucker** [comment]
Can we at least get a metadata update to explicitly state that this cookbook requires the mysql cookbook at version 6+?  This would save a lot of time debugging when using a lower version of the mysql cookbook and attempting to use this one.

**Comment by someara** [comment]
Updated to depend on mysql ~> 6.0 in 1.0.2

**Comment by eric-tucker** [comment]
Thanks!
