### ISSUE TITLE
Chef supermarket release without GitHub update

### ISSUE THREAD

**Issue by Poohblah** [sinfomicien/mysql2_chef_gem#39]
Looks like the latest version of this cookbook on the supermarket is 2.0.0 (with some major changes that broke our cookbooks, but that's a different discussion), but the corresponding changes have not been pushed to this repository.

**Comment by tas50** [comment]
@Poohblah Sorry about the lack of github update. I pushed to the wrong repo. I've updated the source repo and released 2.0.1 with additional documentation
