### ISSUE TITLE
Add shorthand provides

### ISSUE THREAD

**Issue by sbuzonas** [sinfomicien/mysql2_chef_gem#4]
Add `provides :mysql2_chef_gem_mysql` and `provides :mysql2_chef_gem_mariadb` to the providers so they can be easily defined by an attribute.

**Comment by slbmeh** [comment]
After playing with this for a little while, it doesn't work how I thought it did. But it would be nice to have a way to go about it like some of the built in hwrps.

**Comment by tas50** [comment]
The 2.0 version of this cookbook reworked the resource with a provides block. Check out the new release
